[theme]
theme = "solarized-dark"
[icons]
icons = "awesome6"

[[block]]
block = "hueshift"
hue_shifter = "gammastep"
step = 100
click_temp = 1900

[[block]]
block = "external_ip"
format = "{country_flag} {asn} '{org}' {ip}"
with_network_manager = false
error_interval = 300
interval = 300

[[block]]
block = "net"
device = "enp.*"
[[block.click]]
button = "left"
cmd = "/run/current-system/sw/bin/urxvt -e nmtui"

#[[block]]
#block = "custom"
#command = "uname -r | sed 's/-arch1.*//g'"
#interval = 600

#[[block]]
#block = "docker"
#interval = 10
#format = "{running}/{total}"

[[block]]
block = "load"
interval = 1
format = "{1m} {5m} {15m}"

#[[block]]
#block = "cpu"
#interval = 1

[[block]]
block = "memory"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

#[[block]]
#block = "time"
#interval = 30
#format = "%m/%d %R"

#[[block]]
#block = "sound"
#format = "{volume}"
#headphones_indicator = true
#[block.mappings]
#"alsa_output.usb-Harman_Multimedia_JBL_Pebbles_1.0.0-00.analog-stereo" = "🔈"
#"alsa_output.pci-0000_00_1b.0.analog-stereo" = "🎧"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

