theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "xrandr"
icons = true
resolution = true

[[block]]
block = "hueshift"
hue_shifter = "redshift"
step = 100
click_temp = 1900 

[[block]]
block = "keyboard_layout"
driver = "xkbswitch"
on_click = "xkb-switch -n"
format = "{layout} {variant}"
interval = 1

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"
allow_missing = true
hide_missing = true

[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker.*"]
interface_name_include = []

[[block]]
block = "external_ip"
format = "{country_flag} {asn} '{org}' {ip}"

[[block]]
block = "nvidia_gpu"
label = "RTX 2080 Ti"
show_memory = true
show_clocks = true
interval = 3

[[block]]
block = "custom"
command = "uname -r | sed 's/-arch1.*//g'"
interval = 600

[[block]]
block = "docker"
interval = 10
format = "{running}/{total}"

[[block]]
block = "custom"
command = "echo -n 'Procs: ' && ps aux | grep -vE \"echo -n 'Processes: '|grep -vE|ps aux|%MEM\" | wc -l"
interval = 15

[[block]]
block = "load"
interval = 1
format = "{1m} {5m} {15m}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "time"
interval = 60
format = "%m/%d %R"

[[block]]
block = "sound"
format = "Vol: {volume}"
[block.mappings]
"alsa_output.usb-Harman_Multimedia_JBL_Pebbles_1.0.0-00.analog-stereo" = "🔈"
"alsa_output.pci-0000_00_1b.0.analog-stereo" = "🎧"
